[package]
name = "requiem_nif"
version = "0.2.0"
authors = []
edition = "2018"

[lib]
name = "requiem_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
socket2 = { version= "0.2", features = ["reuseport"] }
nix = "0.20"
quiche = "0.7.0"
crossbeam-channel = "0.5"
