[package]
name = "requiem_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "requiem_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
once_cell = "1.5.2"
parking_lot = "0.11.1"
quiche = "0.6.0"
