[package]
name = "requiem_nif"
version = "0.2.0"
authors = []
edition = "2018"

[lib]
name = "requiem_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
once_cell = "1.5"
parking_lot = "0.11"
ring = "0.16"
quiche = "0.6.0"
mio = { version = "0.7", features = ["os-poll", "net"] }
